task: 'Ant-v4'
seed: 0
buffer_size: 4096
hidden_sizes: [64, 64]
lr: 0.0003
gamma: 0.99
epoch: 100
step_per_epoch: 30000
step_per_collect: 2048
repeat_per_collect: 10
batch_size: 64
training_num: 64
test_num: 10
rew_norm: True
state_with_time: True
ent_coef: 0
vf_coef: 0.25
gae_lambda: 0.95
bound_action_method: 'clip'
lr_decay: True
max_grad_norm: 0.5
eps_clip: 0.2
dual_clip: Null
value_clip: 0
norm_adv: True
recompute_adv: 1
history_len: 8
logdir: 'log'
render: 0.0
device: 'cuda'
logger: 'tensorboard'
watch: False
wandb_project: "mujoco.benchmark"
resume_path: Null
actor_type: 'MLP'
critic_type: 'MLP'
