task: 'WindyGrid'
seed: 0
eps_test: 0.005
eps_train: 1.
eps_train_final: 0.05
buffer_size: 100000
lr: 0.0005
gamma: 0.99
n_step: 3
target_update_freq: 500
epoch: 100
step_per_epoch: 20000
step_per_collect: 2048
update_per_step: 0.1
batch_size: 128
training_num: 32
test_num: 10
logdir: log
render: 0.
device: "cpu"
history_len: 8
logger: tensorboard
wandb_project: atari.benchmark
state_with_time: False
model: 'MLP'
mlp_hidden_size: [256, 512]
cde_hidden_size: 64
resume_path: Null
resume_id: Null
expr_id: 12345
